# Generated by Django 5.0.6 on 2024-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_options_article_scraped_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.CharField(
                choices=[("Manual", "Manual"), ("Scraped", "Scraped")],
                default="Manual",
                max_length=20,
            ),
        ),
    ]
