version: "3.9"

services:

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  web:
    build:
      context: .
    volumes:
      - ./:/code
      - ./media:/code/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             gunicorn blog_service.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - .env.prod
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ./media:/code/media
    depends_on:
      - web
